name: ddpm-explai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - einops=0.6.1
  - matplotlib=3.7.2
  - numpy=1.23.5
  - pyyaml=6.0
  - pytorch=1.11.0
  - torchvision=0.12.0
  - tqdm=4.65.0
  - pip
  - pip:
      - opencv-python==4.8.0.74  # If conda doesn't provide exact build
